require("nvim_config.plugins.lazy")
require("nvim_config.plugins.reqs")
require("nvim_config.plugins.gitsigns")
require("nvim_config.plugins.lualine")
require("nvim_config.plugins.telescope")
require("nvim_config.plugins.treesitter")
require("nvim_config.plugins.lsp")
require("nvim_config.plugins.dap")
